### ISSUE TITLE
Turn off radium

### ISSUE THREAD

**Issue by deser** [negomi/react-burger-menu#111]
Hi Guys, is it possible to make Radium dependency optional? 
If somebody passes via props radium={true} then it would return return Radium(React.createClass({. Otherwise it would return just React.createClass({

**Comment by negomi** [comment]
Hi @deser,

This isn't currently possible, and there are a couple of reasons why not:

1. Radium provides automatic browser prefixing. Without it, browser support for several of the animations would be worse.
2. Secondly, the menu uses Radium to compose styles. It allows elements inside the menu to receive an array of style objects, and override the defaults as necessary, which is how custom styles are applied.

Disabling the Radium dependency would therefore reduce browser support, and also remove the ability to pass custom style objects, so I wouldn't want to build in this option without a very good reason.

I know there have been some problems with using custom elements inside the menu caused by Radium, but there are workarounds for this (see https://github.com/negomi/react-burger-menu/wiki/FAQ#i-want-to-use-custom-components-inside-my-menu-but-this-breaks-firefox). I'm not currently aware of any other benefits of removing the Radium dependency.

**Comment by deser** [comment]
>>Radium provides automatic browser prefixing. Without it, browser support for several of the animations would be worse.

This could be done via autoprefixer.

>> Secondly, the menu uses Radium to compose styles. It allows elements inside the menu to receive an array of style objects, and override the defaults as necessary, which is how custom styles are applied.

Due to this I have to rewrite styles in CSS via !important which is bad. I know I can place rewrite styles via property but this is not flexible ( for example I have some scss variables which control `z-index` therefore I need to override styles of burger menu via css)

Actually I've rewritten this package without radium in an hour and there are lot of benefits (as minimum twice less package size).

**Comment by negomi** [comment]
Awesome, good for you. Well if you feel like submitting your changes in a PR then I would be happy to consider merging :)

**Comment by nickdima** [comment]
A "radium free" version wouldn't be a bad idea.
There are a lot of css-in-js react libs out there and every component using different ones makes an app to unnecessary grow in size. Too bad the React community didn't settle on one solution yet. :(
Regarding browser prefixing, probably most of the apps already have something in place for that.

Thanks for building such a great component!
