### ISSUE TITLE
Submenu

### ISSUE THREAD

**Issue by lcnsir** [negomi/react-burger-menu#116]
Hi 

Is there have some examples to make submenus in Menu by using react-burger-menu,

like 1,2,3 level submenus. for example.

-----1
   ------2
      --------3.1
      --------3.2

**Comment by negomi** [comment]
Hi @lcnsir, you can use any structure of components or elements inside the menu. I don't have a specific example of this, but you could build a nested tree of submenus to pass as children, or have submenus that show on hover etc.

Depending on what you do, it might behave weirdly with animations that animate child elements (e.g. stack) but should be fine otherwise.
