### ISSUE TITLE
Double click when menu is open doesn't close menu

### ISSUE THREAD

**Issue by Ssabin-devalore** [negomi/react-burger-menu#136]
Hi , 

I'm using this menu in my React app.
When the menu is open and you double click outside his area it is starting to close and then reopens quickly.

**Comment by negomi** [comment]
Hi @Ssabin-devalore, this is the expected behaviour. If the overlay is still visible, any click on the overlay will 'toggle' the menu. So if it's closing, you need to wait for the animation to finish, or a second click will toggle it open again.

If you need to be able to double click outside the menu without triggering the toggle event, you could consider using the `noOverlay` prop to disable the overlay.
