### ISSUE TITLE
Page wraps not working

### ISSUE THREAD

**Issue by mmarovich** [negomi/react-burger-menu#153]
In order to do this I did create-react-app, and implemented a side bar component, and then in the app.js I passed in the proper props, along with the proper id tags.

Here is my code for the Sidebar:
```
import React, { Component } from 'react';
import { push as Menu } from 'react-burger-menu'

import './Sidebar.css';

class Sidebar extends Component {
  showSettings (event) {
    event.preventDefault();
  }

  render () {
    return (
      <Menu>
        <a id="home" className="menu-item" href="/">Home</a>
        <a id="about" className="menu-item" href="/about">About</a>
        <a id="contact" className="menu-item" href="/contact">Contact</a>
        <a onClick={ this.showSettings } className="menu-item--small" href="">Settings</a>
      </Menu>
    );
  }
}

export default Sidebar;
```
and here is my code for the app:
```
import React, { Component } from 'react';

import Sidebar from './components/Sidebar';
import logo from './logo.svg';
import './App.css';

class App extends Component {
  render() {
    return (
      <div id="outer-container" className="App">
          <Sidebar pageWrapId={ "page-wrap" } outerContainerId={ "outer-container" } />
          <main id="page-wrap">
            <div className="App-header">
              <img src={logo} className="App-logo" alt="logo" />
              <h2>Welcome to React</h2>
            </div>
            <p className="App-intro">
              To get started, edit <code>src/App.js</code> and save to reload.
            </p>
          </main>
      </div>
    );
  }
}

export default App;
```

**Comment by negomi** [comment]
Hi @mmarovich, you're passing those props to your `Sidebar` component, but not through to the `Menu` component, which `Sidebar` renders.

In the `render` method of your `Sidebar` component, you need either pass each prop individually to `Menu`, or you can use the spread operator shorthand to pass all of them:

```js
render () {
  return (
    <Menu {...this.props}>
      <a id="home" className="menu-item" href="/">Home</a>
      <a id="about" className="menu-item" href="/about">About</a>
      <a id="contact" className="menu-item" href="/contact">Contact</a>
      <a onClick={ this.showSettings } className="menu-item--small" href="">Settings</a>
    </Menu>
  );
}
```

**Comment by mmarovich** [comment]
Okay! That works!  : )  I don't know how that could be made clearer on the cods.   <Menu /> implies that it's outside of the Menu component, rather than <Menu></Menu>.  Either way though, it totally works now.  There are a couple of other things that I'm not sure you'd be interested in.

Using the exact same code, if you do "bubble" there is a glitch where the scroll bar is in the middle of the menu.  Also, the scroll bar, period, seems to always be there.  The height of the bm-item-list is 100%, bm-menu is 100%, bm-menu-wrap is 100%.... I'm trying to think of why this happens and the best way to fix it.

Thank you so much for your response!!

**Comment by negomi** [comment]
Awesome!

`<Menu />` and `<Menu></Menu>` are the same thing; the former is just written in self-closing component form (see https://facebook.github.io/react/docs/jsx-in-depth.html for another example/explanation of that).

With the scrollbar problem, it's hard to say exactly what's going on without seeing it, but I would start by identifying which element has the scrollbar. Then you can modify its width/height accordingly. If it's always there even with non-scrolling content, that would suggest you have `overflow: scroll;` applied rather than `overflow: auto;`. That problem doesn't exist on the demo page, so I'd then compare your version to the demo version and try to figure out what's different.

Hope that helps! Going to close this for now as the original issue is resolved.
