### ISSUE TITLE
How to modify base styles?

### ISSUE THREAD

**Issue by alveshelio** [negomi/react-burger-menu#175]
Hi,

First of all, congratulations on the great component you've created, great work.

I'd like to know if it is possible to modify the base styles, right now there are a lot of inline styles and I was wondering if there would be a way to overwrite them.

For example, I'd like to modify the display from fixed to absolute, change the height of the menu wrapper, etc.

Thanks.

**Comment by negomi** [comment]
Hi @alveshelio, glad you like the component!

When you say base styles, I'm assuming you mean the ones not mentioned in the [styling section of the docs](https://github.com/negomi/react-burger-menu#styling).

Some of the inline styles (heights, positioning etc.) are necessary to make the animations work properly, so changing them could have unexpected results, which is why it's not officially exposed/encouraged. You can always override these styles with CSS using `!important` though.

Does that help?

**Comment by negomi** [comment]
Closing as no response - feel free to let me know if this is still an issue.

**Comment by ClaraChaouat** [comment]
> Hi @alveshelio, glad you like the component!
> 
> When you say base styles, I'm assuming you mean the ones not mentioned in the [styling section of the docs](https://github.com/negomi/react-burger-menu#styling).
> 
> Some of the inline styles (heights, positioning etc.) are necessary to make the animations work properly, so changing them could have unexpected results, which is why it's not officially exposed/encouraged. You can always override these styles with CSS using `!important` though.
> 
> Does that help?

Thanks It helped me a lot :).
