### ISSUE TITLE
sidebar的点击控件在哪

### ISSUE THREAD

**Issue by followyong** [negomi/react-burger-menu#181]
怎么样才能控制点击的位置和被点击的对象，点击整个页面的任何地方侧边栏都会弹出来

**Comment by jeffry0926** [comment]
I like the same question, want to know the top of the customBurgerIcon click event location

**Comment by negomi** [comment]
Hey @followyong, sorry for my Chinese skills :)

Not sure if you mean:
1. You want to make the sidebar open by clicking anywhere
2. The sidebar is opening when you click anywhere, and this is a problem

Feel free to push a small repo to demonstrate the issue if that helps.

**Comment by negomi** [comment]
A friend helped me to translate, and I believe your problem is that you haven't added styles yet.

Check out https://github.com/negomi/react-burger-menu/wiki/FAQ#i-imported-the-menu-but-the-burger-icon-isnt-showing-and-the-menu-opens-when-i-click-anywhere

Please re-open if you're still having trouble!
