### ISSUE TITLE
Elastic is hardcoded to animation the page with a 100px offset

### ISSUE THREAD

**Issue by goldensunliu** [negomi/react-burger-menu#207]
currently, elastic.js is hardcoded to shift page 100px instead of using the width.

https://github.com/negomi/react-burger-menu/blob/master/src/menus/elastic.js#L34

**Comment by goldensunliu** [comment]
https://github.com/negomi/react-burger-menu/pull/206

**Comment by negomi** [comment]
Hey @goldensunliu! That 100px is actually intentional - the elastic animation is designed to push the page just a little bit, rather than the width of the whole menu (like push, for example).

I think the idea is that just the animated 'curve' part looks like it is pushing the page, and the width of that part is only 100px.

Hope that makes sense!
