### ISSUE TITLE
Control the time the animation takes? 

### ISSUE THREAD

**Issue by jameschetwood** [negomi/react-burger-menu#220]
Is there a way to control how long the menu animation takes? 

Im currently doing with this a CSS override. Its working but I'm wondering if this is the proper way or if there is a cleaner solution?  

```
.bm-overlay,
.bm-menu-wrap {
	transition-duration: .3s !important;
}
```

**Comment by negomi** [comment]
Hi @jameschetwood,

Great question, that is currently the best way to do this (see answer to https://github.com/negomi/react-burger-menu/issues/216).

I might add a prop-based way to do this in future, but it would mean dynamically calculating other transition values for some of the animations.

**Comment by dspacejs** [comment]
Perhaps @jameschetwood's solution could be added to the README in the meantime? I imagine it'd be a common issue.

**Comment by Offirmo** [comment]
I would also recommend lowering the default animation time. It feels a bit slow. Any other opinion?

**Comment by dspacejs** [comment]
@Offirmo agreed

**Comment by negomi** [comment]
There's already a question in the FAQ about this so I added the CSS solution there: https://github.com/negomi/react-burger-menu/wiki/FAQ/_edit#can-i-change-the-transition-property-of-the-menu

I wouldn't lower the default animation time at this point because it would be a breaking change and I don't think it's enough to warrant a 3.x release. Hopefully this workaround is helpful though.
