### ISSUE TITLE
Flickering issue with right aligned reveal menu. Issue with Firefox & Safari

### ISSUE THREAD

**Issue by sean-wilk** [negomi/react-burger-menu#228]
It seems that when you have the reveal menu on the right hand side there is a flicker at the end of the animation when closing the drawer. I have checked it in Firefox, Chrome and Safari and Chrome seems to be fine but the other two have the issue. The issue occurs on both my site I am developing and on your demo site.

Is there a fix for this?

**Comment by negomi** [comment]
Hey @seantacular,

Thanks for the report - which versions of Firefox and Safari are you seeing this in? And which animation are you using?

**Comment by JustinMoser** [comment]
I second this issue for the right hand reveal menu - There is a flicker on Safari and firefox as far as I can see.

**Comment by dfilaretti** [comment]
Hello, 

I noticed a similar issue today on Cordova/Android, and during my investigation Google brought me here (at the time I didn't realise that the glitch was also on Safari and Firefox but I tested it now and can confirm). 

Since it's been a while this has been reported/discussed I was wondering, has anybody found a fix or perhaps a workaround? 

Thanks in advance, 
Dan
