### ISSUE TITLE
Esc key only clears the last menu on page if multiple instances are on page

### ISSUE THREAD

**Issue by tlockAOB** [negomi/react-burger-menu#233]
Using the component twice, for instance: one left-hand opening menu, one right-hand opening menu, the default behavior of Esc closing the menu only gets applied to the second menu.

(using push animation with page wrappers)

It would be nice if this was coupled more tightly so that any number of menus could be loaded up on a given page.

**Comment by negomi** [comment]
Hi @tlockAOB, thanks for the request!

I think the most flexible way to do this would be to let you optionally pass a custom `window.onkeydown` handler (instead of having this component handle the close on Escape functionality). That way, each application can simply have control over how it closes its own menu(s).

I just implemented this and published it in v2.4.0 (see https://github.com/negomi/react-burger-menu#custom-windowonkeydown-handler).

Hopefully this solves your problem - let me know if not :)

**Comment by kimchirichie** [comment]
Reading through the menu factory, I noticed the events were overwriting previous onkeydown handlers. 
menuFactory.js#L189
`window.onkeydown = this.listenForClose.bind(this);`

whether this is intensional or not is unknown to me. however, using `window.addEventListener(...)` seems more reasonable here
