### ISSUE TITLE
Fixed header disapears with reveal menu even with all the correct markup (page-wrap and outer-container)

### ISSUE THREAD

**Issue by verzola** [negomi/react-burger-menu#235]
Hi! I am using reveal menu animation and my website header is fixed. I followed the documentation and FAQ and still the header disapears when I open the burguer menu:

Menu closed:
![capture3](https://user-images.githubusercontent.com/2985522/38177994-979cabee-35df-11e8-997b-4388b030144c.PNG)

I click and Header disapears
![capture2](https://user-images.githubusercontent.com/2985522/38177996-9d6b4350-35df-11e8-962c-d3a7e4e95cac.PNG)

page-wrap and outer-container markup:
![capture4](https://user-images.githubusercontent.com/2985522/38177997-a208c2f2-35df-11e8-8d13-4a97cd8ddd71.PNG)

Header with menu markup:
![capture5](https://user-images.githubusercontent.com/2985522/38178001-acbc623a-35df-11e8-9eb9-bbc91c3befaf.PNG)

**Comment by negomi** [comment]
Hey @verzola,

Because of the way the reveal animation works, having a fixed header is going to be a bit tricker in this case.

The first thing I notice is that the Menu seems to be inside your fixed header - putting the menu inside a fixed element is likely to result in weird behavior. It's better to keep it separate, and just make it appear like it's inside visually.

That's not the main issue for you though - the reason you can't see your header is z-index. Because reveal works by giving the page-wrap element a higher z-index than the menu (1200 in this case), you would need to give your header a z-index > 1200 for it to be visible.

However, because fixed positioning is relative to the viewport and not the containing element, this will create the new issue that your header is now covering the top of the menu when it's open (which has to have a lower z-index than the page-wrap for the reveal animation to work, so this is why it's a tricky problem with this animation) :)

A few suggestions for solving this:
1. Apply the same transition/transform to your header element as the page wrap when the menu opens/closes. You can find those here: https://github.com/negomi/react-burger-menu/blob/master/src/menus/reveal.js#L42
2. Put your header inside page-wrap, and position it using absolute instead of fixed positioning, giving it the illusion of being fixed. Similar to this: https://codepen.io/anon/pen/LdmvGM?editors=1100
3. Put your header inside page-wrap, leave it with fixed positioning, and take advantage of this hack (the parent component already has the correct translateZ property so you don't need to do anything there): https://stackoverflow.com/questions/6794000/fixed-position-but-relative-to-container/15885486#15885486 (it works for me in Chrome, but I don't know how reliable it is/how many browsers you need to support so I will let you decide)

Let me know if this helps!

**Comment by verzola** [comment]
I tried putting the header inside the page-wrap but the header still disapears if I am not at the top of the page.

Putting Menu outside the header and applying the correct z-index worked (the header does not move with the rest of the content but that's ok for me), but that created yet another issue that the burger menu icon now is not fixed. It only appears on the top of the page:

On the top of the page:
![screenshot from 2018-04-02 13-05-31](https://user-images.githubusercontent.com/2985522/38203861-00fe28fa-3677-11e8-9583-2cbccbbeb69a.png)

Scrolling a bit:
![screenshot from 2018-04-02 13-06-12](https://user-images.githubusercontent.com/2985522/38203871-086de13e-3677-11e8-8911-9e66157714db.png)

Adding position: fixed; left: 0 and right: 0 to the parent element of burgerButton in Chrome Developer Tools seems to solve the issue, how can I pass a custom style for this element?

https://github.com/negomi/react-burger-menu/blob/master/src/menuFactory.js#L267

**Comment by negomi** [comment]
Does applying `position: fixed;` to `.bm-burger-button` not work? That should take the button out of the flow of elements and you shouldn't need to touch its parent. It's hard to tell exactly what's wrong without seeing your code, but it seems like something else is the root of the problem.

If you really want to style its parent, you can target it with `.bm-menu-wrap + div`.
