### ISSUE TITLE
Page scroll position is reset by menu

### ISSUE THREAD

**Issue by tim-soft** [negomi/react-burger-menu#240]
After triggering a menu, the scroll position of `<div id="page-wrap">` gets reset back to the top.

So if you've scrolled down a page and open/close the menu, you'll be back at the top of the website.

edit: Things seem to work as expected in the demo with `Elastic`, maybe this has something to do with my styling. 

possibly related as the page is still scrollable https://github.com/negomi/react-burger-menu/issues/197

edit 2: Yep, it was my styling. I had to add a height resembling the body height and an overflow property on the page-wrap

```html
<div id="outer-container" style={{ background: '#404040', height: '100vh' }}>
    <main id="page-wrap" style={{ height: '100%', overflow: 'auto'}}>
    </main>
</div>
```

**Comment by negomi** [comment]
Hi @tim-soft,

You're right that extra styling is needed to fix this issue (and stop the page scrolling while the menu is open). 

Unfortunately I can't build a solution into the component that will work for everyone, because not every animation requires the page wrap element. However, I have added a suggested solution to the FAQ: https://github.com/negomi/react-burger-menu/wiki/FAQ#my-page-content-is-still-scrollable-when-the-menu-is-open

Thanks for letting me know about this!

**Comment by pasleto** [comment]
Hi, i have same issue. But your solution doesnt work for me. I tried to make my app styled same as example page, keeps scrolling on top? Any recomendations?

**Comment by pasleto** [comment]
> Hi, i have same issue. But your solution doesnt work for me. I tried to make my app styled same as example page, keeps scrolling on top? Any recomendations?

Okey, i got it. I missed height: 100%; on root component. :)
