### ISSUE TITLE
Always open menu from the top entry

### ISSUE THREAD

**Issue by saraervik** [negomi/react-burger-menu#247]
Hi!

I wonder if it is possible to disable the "history" of the burger menu?

My burger menu is quite long and currently, if I scroll down in menu and then close it. The menu will reopen at the position I last viewed it. Do you have any suggestions how I can make it always open from the top entry, not scrolled down?

Thank you for a useful library 😊

**Comment by negomi** [comment]
Hi @saraervik,

Sure! The problem is that when the menu 'closes', it just gets moved out of the viewport rather than unmounted, so won't reset anything (including the scroll position) by default.

What you can do is use the [`onStateChange`](https://github.com/negomi/react-burger-menu#state-change) prop to detect the close event, then reset the scroll position in the callback function. Something like this:

```js
// This is the element that scrolls when your menu has a lot of items
const scrolledElement = document.querySelector('.bm-menu');

const onStateChange = (state) => {
  // Only reset scroll position when state changes to closed
  if (!state.isOpen) {
    // Optional timeout if you want to wait for the menu to disappear
    setTimeout(() => {
      // Reset scroll position to 0
      scrolledElement.scrollTop = 0;
    }, 500);
  }
};

<Menu onStateChange={onStateChange} />
```

**Comment by saraervik** [comment]
Thank you for your help!
