### ISSUE TITLE
Ability to listen for open/close

### ISSUE THREAD

**Issue by nvarchar** [negomi/react-burger-menu#25]
Is it possible to listen for the menu changing states? Thanks.

**Comment by negomi** [comment]
Hey @nvarchar, not fully at the moment. Ideally, the menu would be stateless and the open/closed state would be determined by passed props.

But as it currently handles its own state, the correct way to listen for open/close would be with a global event system. The problem is that this system could be implemented differently by different projects, so the component can't know ahead of time how it should broadcast these events.

There might be a way of restructuring the component to make this possible - I'll have a think.

**Comment by gregory90** [comment]
@negomi how about passing callback through props (onMenuStateChange or something) which would be invoked when menu changes its state?

Right now I can use isOpen prop to open/close menu from the outside, but when I click on overlay or X button, menu closes but my state is not synced with burger menu anymore. Callback would solve this problem.

**Comment by negomi** [comment]
@gregory90 yes, that would work. It felt unnecessary as part of that PR but I think passing a callback might be the best option at this point. I'm planning to implement it soon.

**Comment by negomi** [comment]
Done! See https://github.com/negomi/react-burger-menu#state-change

**Comment by gregory90** [comment]
Thanks! :)

**Comment by swordsreversed** [comment]
I can't quite figure out how to use this, the example just returns the state, i'm not sure of the purpose of that. I tried to update the state using the callback but it seems to crash the browser (seem like an infinite loop?)

`isMenuOpen() {
    this.setState({isOpen: !this.state.isOpen});
  }`

I guess i'm missing something, so how do you keep the state in sync?

**Comment by negomi** [comment]
Hey @swordsreversed! Yep, the code above will cause an infinite loop, because every time the state changes, you're re-rendering the menu with the opposite state, causing the state to change again, and so on.

The kind of situations where you might need `onStateChange` would be if you wanted to trigger some other change somewhere else in your application when the menu opened or closed, but unless you're trying to do something like this, you don't need to use it (or `isOpen`) at all for normal operation of the menu.
