### ISSUE TITLE
How to add two menubars

### ISSUE THREAD

**Issue by NelsonMedinaSilva** [negomi/react-burger-menu#250]
So, I need to add two menu bars, one on the left and the other on the right.
What I did was import the menu twice, first as Menu and then as Menu 2 and in the first one pass by props "left" and "right" to the second one. Either way, I only see the one on the right. Any clue?

```
class App extends Component {
    constructor(props){
        super(props);

        this.state = {

        }
    }

    render() {
        return (
            <div>
                <Menu left >
                    <a id="home" className="menu-item" href="/">Home</a>
                    <a id="about" className="menu-item" href="/about">About</a>
                    <a id="contact" className="menu-item" href="/contact">Contact</a>
                </Menu>
                <Menu2 right>
                    <a id="home" className="menu-item" href="/">Home</a>
                    <a id="about" className="menu-item" href="/about">About</a>
                    <a id="contact" className="menu-item" href="/contact">Contact</a>
                </Menu2>
            </div>
        );
    }
}
```

**Comment by negomi** [comment]
Hi @NelsonMedinaSilva,

A few pointers:
1. There's no `left` prop (left positioning is the default) so you can remove that.
2. The problem could be to do with your importing. You don't need to import the component twice; just import it once and include `Menu` twice in your code, passing the `right` prop to your right menu.
3. It could also be a styling issue - check you're actually positioning the burger icon on the right for the right menu, otherwise it could be hidden under the other one, and look like it's not there.
4. There is some added complexity if you want the Escape key to work for both menus - see https://github.com/negomi/react-burger-menu/issues/233 for more info.

Hope that helps, let me know if not! :)

**Comment by negomi** [comment]
@NelsonMedinaSilva,

Correct. You'll have to pass a different class to each menu, and then use the provided classes scoped inside that, like this:

```js
<Menu className='menu-1' />
<Menu className='menu-2' right />
```
```css
.menu-1 .bm-burger-button {
  position: fixed;
  width: 36px;
  height: 30px;
  left: 36px;
  top: 36px;
}

.menu-2 .bm-burger-button {
  position: fixed;
  width: 36px;
  height: 30px;
  right: 36px;
  top: 36px;
}
```

**Comment by bakhansen** [comment]
@negomi 

I could only get your solution to work if I wrapped each Menu in a div:

```
<div className='menu-1' >
    <Menu />
</div>
<div className='menu-2' >
    <Menu right />
</div>
```
