### ISSUE TITLE
Enable vertical scrolling on page wrap

### ISSUE THREAD

**Issue by willbryk720** [negomi/react-burger-menu#253]
Hi, 

How would we make it such that we can actually make the body of the page wrap scrollable? I am using the scale-rotate version. For the demo page, I've tried to add style={{overflow: "scroll"}}, and disable the overflow auto in the css, and a bunch of other things, but only the menu is scrollable and not the page.

I've only seen issues related to disabling scrollable on the page, but I actually want to enable it!

**Comment by negomi** [comment]
Hi @willbryk720,

You mean you want the page to be scrollable while the menu is open? Adding `overflow: auto;` to the page-wrap element does make it scrollable, but it could be that it's not working because the overlay is on top. You can disable the overlay by passing the `noOverlay` prop.

If I remove the overlay, I can do this on the demo page:

![react-burger-menu](https://user-images.githubusercontent.com/3727684/42139168-77de6e0a-7d3d-11e8-87b1-fad1e3295bb5.gif)

Does that help?

**Comment by willbryk720** [comment]
Thanks for the quick reply! That's exactly the behavior that I wanted. But for some reason, it's not working for me. I'm the using the demo exactly as it came, except I'm putting noOverlay which is indeed disabling the overlay and I'm putting style={{overflow: "auto"}} inside the page-wrap id.

Is there something else I should do?

**Comment by negomi** [comment]
Ah yes, I know what's happening. Because the menu uses inline styles, it's overwriting your `style={{overflow: "auto"}}`.

The easiest way to get around this would be to use CSS and do `overflow: auto !important;` if that's possible for you.

I could look at adding an extra prop to the menu (`allowPageScroll`) or something but I likely won't have time to work on it for a while, so overriding with CSS would be the quickest and easiest fix.
