### ISSUE TITLE
burger button z-index is clobbered on creation

### ISSUE THREAD

**Issue by talexand** [negomi/react-burger-menu#27]
There's an inline style in the burger button creator (https://github.com/negomi/react-burger-menu/blob/1225728690d680a6f9df79a08bafd465d4857306/src/BurgerIcon.js#L44) that clobbers any settings made in CSS from the outside. What's that style doing, and is there a workaround you'd recommend if the button needs to have a different z-index in the page?

**Comment by negomi** [comment]
Hey @talexand, the reason that style exists is because for some of the animations (specifically the ones that shift other elements around), opening the menu changes the z-order such that the icon disappears.

I could update the component to not add this style for menus that don't have this problem (slide, stack or bubble), but you should be able to use `!important` to override it as a workaround for now.

**Comment by talexand** [comment]
Ahh okay. After digging into the source I can see that there's a lot of magic going around these geometries. I can work something out for my specific application in the meantime. Thanks for making such a sweet component!
