### ISSUE TITLE
Customize transition-duration?

### ISSUE THREAD

**Issue by kjs3** [negomi/react-burger-menu#29]
I'd like this and will submit a PR if it's welcome.

I'm forcing a 250ms slide transition using `!important` in css at the moment but it would be nice to have this as a prop.

**Comment by negomi** [comment]
Hey @kjs3, nice idea! I was actually thinking about making it possible to pass in a styles object for the whole component (to allow people to avoid writing separate CSS if they want), so this could fit nicely with that approach.

Customizing `transition-duration` via a prop is slightly more complicated than it sounds because several of the menu animations have subtly different transition behavior (with some requiring delays/moving more than one element etc.). So I'd be reluctant to add a new prop just for this, but I think it'd be awesome as part of a bigger 'styles' prop implementation.

**Comment by negomi** [comment]
This is now possible for Slide (see https://github.com/negomi/react-burger-menu/wiki/FAQ#can-i-change-the-transition-property-of-the-menu), but this approach doesn't work reliably for the other animations. I think this will be enough to solve it for your use case at least :)

**Comment by matejstrasek** [comment]
Any way I could style the background of overlay in push animation? Don't really like the gray color that covers it and would just like to make the overlay transparent. Currently using !important, but solution that is similar to transition of the menu would be way better.

**Comment by negomi** [comment]
Hey @matejstrasek, sure, this should be straightforward to implement. I'll get a release out in the next day or so.

**Comment by negomi** [comment]
Just released v1.5.2, which allows custom overlay styles to be passed to the `styles` prop (see https://github.com/negomi/react-burger-menu/commit/4fe893731fdecd839b535222dcf22bf6d2147198).

**Comment by matejstrasek** [comment]
That was really fast, great, thanks!

Maybe not a place to put it, but I am doing another similar workaround using !important to add custom svg to cross button. The customIcon solution that is already done for the burger ic . would be also really great for cross button. :)

**Comment by negomi** [comment]
I think that would be a good addition. I'm going to create a new issue for it so it doesn't get lost here :)

Thanks for the suggestion!

**Comment by andrewmclagan** [comment]
Can you possibly link in the new issue, thanks!

**Comment by matejstrasek** [comment]
@andrewmclagan #40
