### ISSUE TITLE
Custom icons, and overlay menu.

### ISSUE THREAD

**Issue by oyeanuj** [negomi/react-burger-menu#30]
Hi @negomi, this plugin looks great! For my particular use-case, I was hoping to support the following features and was wondering if the plugin supports it, plans to support it or how hard would it be for me to fork it to add the functionality - 

1. Custom burger menu icon. More specifically, I was also looking to to add the word 'menu' next to the icon. 

2. An overlay instead of the side bar. Or would it be possible to instead pass in a modal component as a child of the Menu and it would render the modal?

An example implementation for both of those can be seen here - http://teehanlax.com/

Thanks again for the plugin!

**Comment by negomi** [comment]
Hey @oyeanuj, thanks for the feedback! In response to your questions:

1. I think this is a great idea. I went with the CSS solution for simplicity, but I was planning to add this as an option at some point because it would be awesome for the menu to work with custom SVG icons, for example.
2. This would also be possible. I think the best way to do it would be to create a new menu (called 'overlay' or similar). It would need to appear from the top and have an appropriate animation. Something like [Bootstrap's modal animation](http://getbootstrap.com/javascript/#live-demo) could be nice. This would be cleaner than trying to adapt any of the current animations to take a modal component as a child, as they're very much designed for sidebars.

If you want to add a 'menu' label next to the icon, you could use a pseudo element for a quick solution. I can add the following CSS to the demo and (with the icon positioned on the right) get a similar effect to your example:
```css
.bm-burger-button::before {
    content: 'MENU';
    position: absolute;
    right: 53px;
    top: 7px;
    color: #373a47;
    font-size: 0.9em;
    font-weight: bold;
}
```
I'll try to get these things into a release soon. Hope that helps!

**Comment by oyeanuj** [comment]
@negomi Just realized, I forgot to say thank you! Thanks for your response, and suggestions :)

And looking forward to the above changes in a release soon!

**Comment by negomi** [comment]
Hi @oyeanuj! It's now possible to pass an image to use as a custom icon (see https://github.com/negomi/react-burger-menu#custom-icon).

I decided not to add an 'overlay' menu, as I'd rather not add more menus to the core component at this point, but I hope the steps above will be helpful if you want to fork it and add one yourself. Thanks again for your suggestions :)
