### ISSUE TITLE
Enhance moving to right

### ISSUE THREAD

**Issue by polishedwp** [negomi/react-burger-menu#313]
Would it be possible to somehow connect the "right" attribute to the CSS? For instance, if I set the menu to "right" the burger icon stays on the left, unless I edit the CSS. It would be helpful if the right attribute would override the CSS as well. 

Otherwise, I move it. I have added to the GatsbyJS default theme and have created a [repo](https://github.com/polishedwp/gatsby-burger-menu).

**Comment by negomi** [comment]
Hey @polishedwp,

I get how this could be useful in the standard case (menu on the left, burger icon also on the left etc.), but because the burger icon positioning is completely up to the user, the menu cannot know what the best right-aligned equivalent would be in every situation. For example, someone could position their burger icon in the center, or somewhere else entirely.

For this reason, I think it's best to leave it up to the user to position the burger icon, then they can put it wherever they choose. Thanks for the suggestion though.
