### ISSUE TITLE
Multiple .js files in the example index.html

### ISSUE THREAD

**Issue by msimonc** [negomi/react-burger-menu#32]
Hi and Thanks for this awesome project,
The example includes example.js and common.js as well as bundle.js,
All the other components I've included in my webpack app so far have all been packed into a single bundle.js file?

**Comment by negomi** [comment]
Hey. This project uses https://github.com/JedWatson/react-component-starter, so that's where this behaviour is coming from.

The idea is that in development, it can take a long time to build a monolithic `bundle.js` if you have a lot of dependencies, and you don't actually need to re-bundle all your external dependencies every time you make a change to your project's code.

It's more efficient to split the code into separate bundles, so the one you have to regenerate over and over in development is much smaller. This article explains it pretty well: https://lincolnloop.com/blog/speedy-browserifying-multiple-bundles/
