### ISSUE TITLE
how to create multi level menu

### ISSUE THREAD

**Issue by vasan19** [negomi/react-burger-menu#321]
Hi i try to create multilevel menu i cant find any doc how to create multilevel menu. help me with sample code.

**Comment by negomi** [comment]
Do you have an example of what you mean by multilevel menu?

**Comment by vasan19** [comment]
i am looking menu like this Negomi
![multilevelmenu](https://user-images.githubusercontent.com/12094719/56486578-b51f4000-64f5-11e9-8672-bd36166ceda7.png)

**Comment by negomi** [comment]
react-burger menu is really just a sidebar container, so you can put anything you want in it.

You could definitely build a custom multilevel menu like that to go inside it, but you would have to Google for examples to learn from, because sample code for that is beyond the scope of this component's documentation.

If you were looking for a package that supports multilevel nested menus out of the box, it looks like there are a few others that support it, e.g. https://www.npmjs.com/package/react-sidenav

Or this one, which you might be able to use inside react-burger-menu: https://github.com/gholme4/react-nested-menu

Good luck!
