### ISSUE TITLE
Perspective in Chrome

### ISSUE THREAD

**Issue by chroth7** [negomi/react-burger-menu#35]
Thanks for the menu, very nice!

I am using it in a small app and I noticed that when using e.g. scale down, the content/fonts look different after using the menu (also happens on http://negomi.github.io/react-burger-menu/ ) I think, if you look closely.

I am no expert on CSS Transform, but it seems to me that setting `perspective` to `1500px` and leaving it so after closing the menu is the problem.

(many stackoverflow threads around this topic, e.g. http://stackoverflow.com/questions/6411361/webkit-based-blurry-distorted-text-post-animation-via-translate3d)

I quickly tried to fix things using 

```javascript
outerContainer: function outerContainer(isOpen) {
		return {
      perspective: isOpen ? '' : '1500px',
    };
  }
```
in https://github.com/negomi/react-burger-menu/blob/master/src/menus/scaleDown.js#L16-L20

This seems to reset perspective after the menu closes (and I get clear fonts again), but the animation is broken, on close, as there is no end point anymore.

Can you reproduce the problem? Do you have any idea how to solve it?

**Comment by negomi** [comment]
Hey @chroth7! Good spot, I hadn't noticed this before.

The problem seems to be caused by `translate3d()` rather than `perspective`. Specifically, it occurs when you set `translate3d(0, 0, 0)` explicitly, which we are doing at the moment, but we can actually get away with just removing that value rather than setting it. This solves the blurry text problem, without having to mess with antialiasing.

I've pushed an updated version (1.4.13) which includes the fix - hope that helps!

**Comment by chroth7** [comment]
@negomi Thanks for the quick feedback and fix! Just tried it, works like a charm. 

Thanks again!
