### ISSUE TITLE
Custom Hamburger menu 

### ISSUE THREAD

**Issue by ozkan-oz** [negomi/react-burger-menu#352]
Hi - quite new to react but is there anyway to have custom hamburger icon. Not just image but with divs and spans

**Comment by negomi** [comment]
Hi @ozkan-oz, yes, you can pass any React element as the `customBurgerIcon` prop.

Alternatively, you can have a custom icon anywhere on your page and trigger the menu with any click event on that element. This method involves a little more code, because you control the state externally, but there is an example of how to do it here: https://github.com/negomi/react-burger-menu/wiki/FAQ#i-want-to-control-the-open-state-programmatically-but-i-dont-understand-how-to-use-the-isopen-prop
