### ISSUE TITLE
Menu doesn't close when clicking on menu item Link

### ISSUE THREAD

**Issue by Suraj151** [negomi/react-burger-menu#360]
with reference of issue https://github.com/negomi/react-burger-menu/issues/231
same happens to me.
in past i used it somewhere and i know that menu works fine without isOpen tag/monitor outside of it.

but for latest version(2.6.13) i don't dig out in whats exactly going wrong

and i found it works fine again when i switched to version 2.5.2

**Comment by jacksonkr** [comment]
I downgraded to `2.5.2` with no success, my menu still stays open.

Is there another way to make sure the menu closes? eg a state change ?

**Comment by jacksonkr** [comment]
Solved this by adding a state parameter

```
constructor(props) {
        super(props);

        this.state = { menuOpen: false };
}
```

and when in my onclick I added

```
loginClick() {
        this.props.history.push('/');
        this.setState({ menuOpen: false });
}
```

`<Slide isOpen={this.state.menuOpen} width={width} pageWrapId="router" outerContainerId="app" id="push" >`

**Comment by jacksonkr** [comment]
Current solution to get menu to close on item click.

Add
```
document.querySelector('.bm-overlay').click()
```

**Comment by handydortmund** [comment]
2.5.2 works for me.... 2.6.13 does NOT close if this.state.menuOpen is set

**Comment by thebarty** [comment]
2.6.13 does NOT work but for me 2.5.2 works

**Comment by negomi** [comment]
Hey all, sorry for the delay on this.

I can't tell exactly why this is happening from the info here, but if anyone can share a repo demonstrating the issue, I'd be happy to take a look and help debug.

**Comment by Suraj151** [comment]
@negomi its far old issue, i don't have set to test it. but it was about if we click on any of the links from opened menu, the menu doesn't close itself (it should close menu window and it was available with version 2.5.2) not in later versions may be.

**Comment by pixelfreak** [comment]
Echoing @jacksonkr, managing our own state and passing `isOpen` isn't closing the menu. The only (hacky) solution so far is to programmatically click the overlay.

**Comment by Neychok** [comment]
I had be struggling the whole day over this issue.
I tried @jacksonkr 's solution but since I am new to React (and Js tbh) his solution by itself didn't fix my issue.
Here's what I did.
1. I added a custom class for the overlay (You could probably skip this step)
`        <Menu
          overlayClassName={"closeMenu"}>`
2. Copy/Paste this code:
 `const closeMenu = () => document.querySelector(".closeMenu").click()`
3. Add closeMenu as OnClick event on every Link:
 `<Link to="/" onClick={closeMenu}></Link>`

And it should work. Here's an example:

```
export default props => {
   const closeMenu = () => document.querySelector(".closeMenu").click()
    return (
        <Menu overlayClassName={"closeMenu"}>
            <Link to="/" onClick={closeMenu}>Home</Link>
       </Menu>
)}
```

**Comment by hdgone** [comment]
@Neychok you should never mutate DOM manually while using React, because React needs to know about all changes made to the DOM in order to build Virtual DOM to compare them later.

To fix the issue, you should manage the menu state yourself (means you should have a separate useState in your component that you'll pass as isOpen prop). Besides you should also provide a onStateChange prop which is a callback that receives current state from menu component:

```
const [open, setOpen] = useState(false);
return (
  <Menu
    isOpen={open}
    onStateChange={({ isOpen }) => setOpen(isOpen)}
  >...your custom children here...</Menu>
)

**Comment by minhmera** [comment]
@hdgone hi brother, u saved my day, thanks so much
