### ISSUE TITLE
How to hide scrollbar in menu?

### ISSUE THREAD

**Issue by fifichaladyniak** [negomi/react-burger-menu#372]
When menu shows up, it comes with big scrollbar next to buttons. I know I probably need to use "overflowY: 'hidden'", but I am not sure where put it.

**Comment by Steague** [comment]
@fifichaladyniak I am not sure what browser you are using but the same thing happened to me in Chome when using the default styling provided in the README. If you are using the styling provided in the README, remove the padding from the `.bm-item-list` element selector. Alternatively, if you would like to keep the left and right padding, you can add a `0` to the padding so that it looks like the following:

```css
.bm-item-list {
  color: #b8b7ad;
  padding: 0 0.8em;
}
```

This got rid of the scrollbar for me.

If you would prefer to use your overflow-y declaration, you can add `overflow-y: hidden !important;` to the `.bm-menu` element selector. The `!important` is required as the element has backed in element styling as part of the component. This is very much a **terrible** hack though and I would recommend the padding declarations mentioned above.

**Comment by fifichaladyniak** [comment]
Ok, thanks for your support :)
