### ISSUE TITLE
burger icon doesn't stay in position

### ISSUE THREAD

**Issue by TOcvfan** [negomi/react-burger-menu#383]
I can't get the burger icon to stay in the top left corner and it's on top of my app, meaning that it covers my text
![burgerIconProblem](https://user-images.githubusercontent.com/11290288/84025196-69df1f80-a98b-11ea-8880-8fc822ecb91a.PNG)

I managed to to move my app to the right with
 `.margin{
    display: flex;
    margin-top: 75px;
    margin-bottom: 25px;
    margin: 0 auto;
    width: 90%;
}
`
and

```
<main id="page-wrap">
     <div className='margin'>
          <Route path={'/'} exact component={Home} />
          <Route path={'/login'} component={Login} />
     </div>
</main>
```
but I cant get the text below the icon, what do I do?

**Comment by negomi** [comment]
Hi @TOcvfan,

Are you using the example styles for the menu? They have `position: fixed;` for the burger icon which is why it covers your text. If you don't want the icon fixed positioned, you can remove that style.

If you do want it fixed, but want your text below the icon, you'd have to add more margin or padding to the top of your `.margin` element.

Hope that helps.

**Comment by TOcvfan** [comment]
okay I remowed the `positin: fixed;` and now it looks like this: 
![burgerIconProblem](https://user-images.githubusercontent.com/11290288/84148083-bcd5d700-aa5e-11ea-90c6-4d071fdaa208.PNG)

and i added these lines to .margin
```
margin-left: 25px;
margin-right: auto;
```
but it didn't work

**Comment by negomi** [comment]
You need to add width to the burger icon as well.

And then something like `padding-top: 50px` to .margin.

I would recommend adjusting your styles in the browser developer tools until you find a combination that works for you.
