### ISSUE TITLE
How to modify the z-index of button

### ISSUE THREAD

**Issue by simron-smwork** [negomi/react-burger-menu#400]
Hi, really appreciate your help and quick replies!
I am trying to make just the burger button (not the whole sidebar menu)  overlap my existing horizontal top navbar. How do I make that happen? 
How will I be able to customize the zIndex of the button?

**Comment by negomi** [comment]
Hi @simron-smwork, you can apply any styles you like to the button.

For z-index to work though, the position property needs to be explicitly set to absolute, fixed, or relative, and your markup structure matters too.

If it's not working, I'd recommend reading up on how z-index works because there are a few gotchas that can make it tricky if you're not aware of them.
