### ISSUE TITLE
How to remove outline on item list wrapper 

### ISSUE THREAD

**Issue by mikebeaudry93** [negomi/react-burger-menu#411]
Im getting an outline on the item list wrapper whenever I open the menu. Sorry if this is a trivial question but how do I remove this? Also, if I click anywhere outside the wrapper the outline disappears.

**Comment by negomi** [comment]
Hi @mikebeaudry93,

That's strange, do you mean the `.bm-item-list` element? Which browser are you seeing this in?

You might be able to hide it with CSS using `outline: none;` but I'm wondering why that element is getting an outline at all.

**Comment by mikebeaudry93** [comment]
Hi Imogen,

Thanks for the reply! Yes, it’s the element you mentioned and I’m seeing it
in chrome.

I tried hiding it like you said with outline: none but it didn’t work. I’ve
attached a photo on how it looks.

**Comment by negomi** [comment]
I don't see anything attached, happy to take a look though (if you can include your devtools open with the element selected in the screenshot, that would be helpful).

**Comment by mikebeaudry93** [comment]
<img width="1354" alt="Screen Shot 2020-10-21 at 2 52 00 PM" src="https://user-images.githubusercontent.com/50886835/96769433-21aa2200-13ad-11eb-9b07-d5133514bc54.png">

**Comment by negomi** [comment]
Ah I see what's happening 😄 

The menu expects you to pass your links/menu items as direct children, but because you're wrapping yours in that `burger-menu-links` div, the menu thinks you are only passing one item (and it focuses the first item by default).

So you have two options:
1. Remove that div and pass your links as children directly (then just the first item will be focused)
2. If you want to keep that wrapper div, you can pass the `disableAutoFocus` prop (this will disable the focus behavior, but that's not recommended because it will make your menu less accessible)

**Comment by mikebeaudry93** [comment]
Thank you so much!
