### ISSUE TITLE
Passing isOpen props to the menu doesn't work

### ISSUE THREAD

**Issue by amitthakkar22288** [negomi/react-burger-menu#42]
i tried passing the isOpen as a props, but the menu doesn't open. i tried debugging and it seems you would want to read the props and update state in the componentWillReceiveProps function? 
`<Menu styles={menuStyles} isOpen={this.state.isMenuOpen}>
            <a id="home" className="menu-item" href="/">Home</a>
            <a id="about" className="menu-item" href="/about">About</a>
            <a id="contact" className="menu-item" href="/contact">Contact</a>
          </Menu>`

**Comment by amitthakkar22288** [comment]
I noticed you fixed this bug, and released a new version 1.5.4. Can this be somehow patched to work with React 0.13?

**Comment by negomi** [comment]
Hey, yeah, I meant to say this bug is fixed in 1.5.4 - thanks for reporting it :)

The last version that worked with React 0.13 is 1.1.6, which is quite old now and doesn't even include this feature. I didn't want to maintain two branches so I decided not to add any new features to that version, but it's available on a branch (called 1.1.6) which you're more than welcome to fork if you'd like to add the feature.
