### ISSUE TITLE
React Burger Menu breaks Firefox

### ISSUE THREAD

**Issue by stanleycyang** [negomi/react-burger-menu#44]
I'm not sure why, but with `react-burger-menu` I get this issue: 

```
TypeError: CSS2Properties doesn't have an indexed property setter for '0'
```

It breaks my react-router and I'm no longer able to navigate within the app

**Comment by negomi** [comment]
Hi @stanleycyang, do you know which line of code is throwing this error? It doesn't happen on the demo page so I'm trying to figure out where best to start debugging.

**Comment by stanleycyang** [comment]
![screen shot 2016-03-08 at 1 30 26 pm](https://cloud.githubusercontent.com/assets/3037893/13617147/fd49b528-e531-11e5-9581-480856b85866.png)

**Comment by negomi** [comment]
Ah, this is because you're using react-router. See https://github.com/negomi/react-burger-menu/wiki/FAQ#why-doesnt-the-link-component-from-react-router-work

I cloned twreporter-react (the project you mean I think?) and checked out the commit before you removed react-burger-menu, added this fix, and it works fine.

Sorry, the FAQs are a bit hidden in the wiki :)

**Comment by cimi** [comment]
I had the same problem because I was using an unwrapped `Glyphicon` from react-bootstrap as the `customBurgerIcon`; wrapping it in Radium fixes it:

```
render () {
  const Menu = BurgerMenu.slide
  const RadiumGlyphicon = Radium(Glyphicon)
  return (
    <Menu customBurgerIcon={<RadiumGlyphicon glyph='chevron-left' />} right>
      <ProfileControls />
    </Menu>
  )
}
```
This was a pain to debug as it's was not clear (at least in my app) that the issue was coming from this component and it weirdly occurs only in Firefox, Chrome tolerates it.

Agreed on the FAQ being hidden, also Google wasn't helpful - I found this issue page with Github search on this repo. What do you think of putting the radium info in the main README?

**Comment by negomi** [comment]
I'm happy to move them to the README. Will do the update when I get some time.

**Comment by kachkaev** [comment]
Git the same issue as well. Was pretty hard to investigate.

**Comment by html5-ninja** [comment]
I had the same issue, I'm using burger menu with react router, I simply wrapped my links in a div
`    <Menu>
                    <div>
                    <Link id="home" className="menu-item" to="/">Home</Link>
                   </div>
     </Menu>
`
hope this help

**Comment by mxs** [comment]
I've tried all of the above methods to get around the issue but only the wrapping of of `Link` in a `div` worked in the end.

**Comment by wlingke** [comment]
It would be nice if this was added to the documentation. Just one line somewhere would do: custom elements as a child of the menu or as a custom icon/etc. may not work due to radium and need to be wrapped in Radium or in a <div> or <span>

**Comment by negomi** [comment]
Hi @wlingke, there is already link in the documentation to the wiki where this issue is addressed: https://github.com/negomi/react-burger-menu/wiki/FAQ#why-doesnt-the-link-component-from-react-router-work

I'm not sure exactly what causes the need for an extra `div` (i.e. when wrapping in Radium is not enough). If I know the reason, I'm happy to add this use case and explanation to the docs.

**Comment by wlingke** [comment]
@negomi Yes I read that but didn't realize it applied to ALL custom elements. Also did not realize it applied other customizable parts - like when specifying a custom icon (I was using `react-fa` for instance). Perhaps that could be noted for people like me who do not have much experience with Radium.

Also it might be worth noting that it seems with some custom elements, even after you wrap it, Radium cannot apply styles to them so we have to specify our own styles via css.

**Comment by negomi** [comment]
So it seems like there are a few things going on here:

> didn't realize it applied to ALL custom elements

When you say 'all custom elements', do you mean all child elements of the menu? As far as I'm aware, you only need to wrap these in Radium if they're react-router `Link` components.

> did not realize it applied other customizable parts - like when specifying a custom icon

So you're saying that when supplying a `customBurgerIcon`, you need to wrap it in Radium? I didn't know this either, and I'm not sure why it would be necessary. Again, the only case I know about is for react-router `Link` components.

> with some custom elements, even after you wrap it in Radium, Radium cannot apply styles to them so we have to specify our own styles via css

Not entirely following here. Is this separate from having to wrap elements in `div`s or `span`s?

I think the easiest thing might be if you could push a sample of code demonstrating the problems you're having up to a repo. Then I can look into it to try to figure out what's going on.

Also feel free to create new issues - there are several different problems raised here, not necessarily all related, and it sounds like some of them could be bugs rather than just lacking documentation.

**Comment by wlingke** [comment]
@negomi The reason why the Link component doesn't work is because Radium doesnt work with custom components (https://github.com/FormidableLabs/radium/tree/master/docs/faq - read: Why doesn't Radium work on react-router's Link, or react-bootstrap's Button, or SomeOtherComponent?) Wrapping Radium around the custom component seems to solve this issue for most of custom components.

So basically anything that the library is applying Radium to will have this issue. I didn't specifically test all the instances, but customBurgerIcon was definitely affected. I was using an `<Icon />` from `react-fa` and it threw the error. 

Similarly, if there are ANY direct children that are custom elements inside `<Menu>` you will have an error thrown.

For example:
```
  (<Menu>
        <Button>button</Button> //some custom button
      <Social size="normal" className={styles.social} /> //some other custom element
  </Menu>);
```

One solution can be to wrap the custom elements with Radium. But this can be annoying (if you have a bunch of custom elements you don't want to have to wrap every one). Instead, just insert a div as such:

```
  (<Menu>
       <div>
        <Button>button</Button> //some custom button
       <Social size="normal" className={styles.social} /> //some other custom element
       </div>
  </Menu>);
```

This works because Radium works on normally html elements. This also works for the customBurgerIcon/customCrossIcon for the same logic.

```
<Menu customCrossIcon={<span><Icon name="times" /></span>}>
```

It's also a workaround if your custom element conflicts with Radium (such as the popular UI library Rebass).

**Comment by cimi** [comment]
> So you're saying that when supplying a customBurgerIcon, you need to wrap it in Radium? I didn't know this either, and I'm not sure why it would be necessary. Again, the only case I know about is for react-router Link components.

@negomi, please see my example above, I had to wrap a react-bootstrap `Glyphicon` without having anything to do with react-router. (I do use react-router in the project, just not in the burger menu). I didn't understand _why_ I had to do that, but it broke FF if I didn't.

**Comment by negomi** [comment]
Hey all, thanks for your input on this (especially @wlingke) - I've now updated the FAQs to include this solution: https://github.com/negomi/react-burger-menu/wiki/FAQ#i-want-to-use-custom-components-inside-my-menu-but-this-breaks-firefox
