### ISSUE TITLE
Replace close button with &times;

### ISSUE THREAD

**Issue by multiwebinc** [negomi/react-burger-menu#447]
Wouldn't it make more sense to do something like:

```
<button aria-label="Close Menu">&times;</button>
```

This way it could easily be styled and even used as the button instead of having a 0 font-size button?

Also, as it is now, when the menu content is longer than the screen height, the button is way too close to the scrollbar:

![image](https://user-images.githubusercontent.com/901732/116799942-ed30c480-aab9-11eb-9d8a-9f0b907c4729.png)

Let me know if you're interested in a PR

**Comment by negomi** [comment]
Hi @multiwebinc,

Completely agree, there are many approaches that would make more sense than what is there currently (though using `&times;` could be too font-dependent to work as a zero-config default).

That said, I'd be wary of changing this now because it'd be a breaking change, but it seems a bit small for a major version bump.

Luckily there are ways to get around the issues you've identified:
1. Adjust the top/right properties of the `bm-cross-button` element so it sits further away from any visible scrollbar
2. Replace the icon, or don't render the default button at all, and use your own custom one instead: https://github.com/negomi/react-burger-menu#custom-icons

Hopefully one of these works for your use case.
