### ISSUE TITLE
[Enhancement] Wave Support

### ISSUE THREAD

**Issue by KerenChandran** [negomi/react-burger-menu#50]
I noticed that the OffCanvasMenuEffects repo has a wave effect. Is it possible to do this now or does this need to be implemented. I really love this component and the effects you currently have!

**Comment by negomi** [comment]
Hey @KerenChandran! I decided not to implement that one originally because I only planned for the menu to appear from the left side of the screen.

It's now evolved so it can be positioned on the right as well, but would take some more refactoring to allow menus that come from the top and/or bottom.

I don't have a lot of time to add new features right now, but I think this would be a great addition so I'm going to leave this here with an enhancement label in case anyone wants to attempt it :)
