### ISSUE TITLE
Externally control open state.

### ISSUE THREAD

**Issue by trungtin** [negomi/react-burger-menu#58]
Thanks for beautiful components, but here my 2 cent, if isOpen props is set on Menu, then it should remove click handle on burger and cross button, and only give two other request function ( (for e.g. onRequestOpen and onRequestClose), otherwise external state would be out-of-sync, right? And what about a props to completely remove burger and cross button (false on customIcon). Thanks, if I find some time, I will make a PR.

**Comment by negomi** [comment]
Hi @trungtin, yes, the `isOpen` prop has been the source of a few weird bugs recently.

I think the problem was trying to keep track of too many things (e.g. old and new props and/or state) when rendering with `this.props.isOpen`. What happens now (since v1.8.2), is that whenever `this.props.isOpen` is supplied, that always becomes the value for `this.state.isOpen`, regardless of anything else. If `this.props.isOpen` is not supplied, then we just toggle `this.state.isOpen` from whatever it was before. I *think* this avoids getting out of sync, unless I'm missing something?

Either way, I like the idea of adding a `customIcon: false` option to remove burger/cross functionality and let the open/closed state be purely controlled externally. I don't have a lot of time to spend on this component at the moment, but PRs always welcome :)

**Comment by aaronsmulktis** [comment]
+1

and yes thank you again for such a great component @negomi.
Seems like ^^^ should fix this, looking forward to trying once it hits npm

Thanks!

**Comment by aaronsmulktis** [comment]
Hey! Thanks so much for all the hard work @negomi.
This thing works beautifully, and I'm using it across a couple projects.

Since updating to 1.8.2 I'm now able to control the position of the menu by passing the prop, but that doesn't seem to update the translate3d CSS property for the pageWrapId, so the page wrapper stays where it is no matter how I control the menu.

Anything I'm missing?

Thanks!

**Comment by negomi** [comment]
Hi @aaronsmulktis, glad you're liking the component!

The latest version is now 1.8.3, which includes additional fixes around the `isOpen` prop. Can you update and see if you're still having the same issue?

**Comment by negomi** [comment]
Hi @trungtin, I have just published v1.8.4 which includes the ability to pass `false` to disable the burger or cross icons, like you suggested.

I also believe the out-of-sync issues with `isOpen` were resolved in v1.8.3, so I think I'm safe to close this issue now. If you're keeping track of state externally, you'll want to use [`onStateChange`](https://github.com/negomi/react-burger-menu#state-change) to keep your external state in sync, in combination with `isOpen`.

Thanks again for your input!
