### ISSUE TITLE
Cannot see the toggle button 

### ISSUE THREAD

**Issue by casche** [negomi/react-burger-menu#64]
What have I done wrong if I cannot see the button? 😞 

<img width="1440" alt="screen shot 2016-05-27 at 5 35 02 pm" src="https://cloud.githubusercontent.com/assets/5832943/15620580/6b688a3c-2431-11e6-90ad-1063ebbd9e11.png">

``` js
import React, {PropTypes} from 'react';
import { push as Menu } from 'react-burger-menu';

const Nav = React.createClass({
  render: function() {
    return (
      <Menu pageWrapId={ "page-wrap" } outerContainerId={ "outer-container" } noOverlay>
        <a id="home" className="menu-item" href="">French</a>
        <a id="home" className="menu-item" href="/">Home</a>
      </Menu>
    );
  }
});

export default Nav;
```

``` js
import React, {PropTypes} from 'react';
import Nav from './common/Nav.js';

class App extends React.Component {
  render() {
    return (
      <div id="outer-container">
        <Nav/>
        <main id="page-wrap">
        </main>
      </div>
    );
  }
}

App.propTypes = {
  children: PropTypes.object.isRequired
};

export default App;

```

**Comment by negomi** [comment]
I'm guessing it's because you haven't supplied any styles yet. The actual `button` element is just there for semantic reasons and is supposed to be invisible.

The classes that let you style the icon are `.bm-burger-button` (for positioning/sizing) and `.bm-burger-bars` (for the visual look of the bars).

See https://github.com/negomi/react-burger-menu#styling :)

**Comment by casche** [comment]
I JUST realized that! I'm sorry @negomi . That's a little confusing I guess, or maybe it's just friday. 

A little off topic, but what if I would like the button somewhere else in the dom? Like If I'm mixing in a bootstrap navbar.

**Comment by negomi** [comment]
If you want to trigger the menu from somewhere else in the DOM, you won't be able to use the native button because it's already integrated into the component.

What you can do is hide the native button, then trigger the menu to render as open/closed when your other button is clicked, by passing the `isOpen` prop (see https://github.com/negomi/react-burger-menu#open-state).

Hope that helps!
