### ISSUE TITLE
react-burger-menu breaks programmatic scrolls

### ISSUE THREAD

**Issue by codeheroics** [negomi/react-burger-menu#85]
Hi,

When react-burger-menu is included on a page, it breaks the ability to programmatically scroll.

For example, in http://negomi.github.io/react-burger-menu/ , after reducing a window, trying to use `window.scrollTo(0, 0)` will never to go top, and `window.scrollY` is always set to 0.

Not scrolling is the expected behavior when the menu is opened, but this happens even with the menu closed (and actually, in my app, it only happens after the menu has been opened at least once)

**Comment by negomi** [comment]
Hi @codeheroics, it's probably to do with what I'm setting/re-setting a value to on `window` to disable scrolling when the menu is opened.

I'll take a look asap - thanks for reporting :)

**Comment by kvnvelasco** [comment]
@negomi how do we disable scrolling when the menu is open?
for longer menus on mobile the menu gets truncated and I cannot scroll.

**Comment by negomi** [comment]
@codeheroics: ah, so this is happening because of the way the component uses container elements for several of the animations. The scroll actually happens on the internal wrapper component (`#page-wrap` in the demo) rather than on `window`. So for programmatic scroll, you would need to set the `scrollTop` property of that element (see https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTop), rather than try to scroll `window` itself.

@kvnvelasco: the menu has automatic scrolling for elements that overflow the container from v1.10.4. In earlier versions, you needed to add `overflow: auto` to the `bmMenu` element to achieve this.

Hope that helps! :)
