### ISSUE TITLE
Overlay css incorrectly positions the overlay when hidden

### ISSUE THREAD

**Issue by CoreyTrombley** [negomi/react-burger-menu#87]
So I guess I am the only person having this issue but, from what I can tell the code [here](https://github.com/negomi/react-burger-menu/blob/v1.9.9/src/baseStyles.js#L13) is placing the overlay on the wrong side.
<img width="1269" alt="screenshot 2016-07-22 12 51 04" src="https://cloud.githubusercontent.com/assets/2028391/17064541/fe41816a-500a-11e6-86d0-2c41ee000653.png">
If I change the `-100%` to `100%` it flips it to the other side. I am not great at css but, I put this [fiddle](https://jsfiddle.net/uskv9o5u/1/) together for reference.
<img width="1277" alt="screenshot 2016-07-22 12 54 40" src="https://cloud.githubusercontent.com/assets/2028391/17064636/7b1ed534-500b-11e6-9364-c01782ce8ad3.png">

**Comment by CoreyTrombley** [comment]
Oh I think the `isOpen` ternary is backwards

**Comment by negomi** [comment]
Hey @CoreyTrombley,

-100% or 100% should have the same effect of getting the overlay off the screen, which is all the aim is here. Your fiddle also shows the expected behaviour.

I'm not sure what's going on in your first screenshot but it's definitely the first time I've seen that happen - if you can put a small example repo together reproducing the issue, I'd be happy to take a look :)

**Comment by negomi** [comment]
I have changed this to `100%` in v1.10.4, so hopefully this has fixed your problem!

**Comment by CoreyTrombley** [comment]
Hey @negomi,

Thank you so much. After further review of my issue. I found that when using `display: flex;` on the parent element of the menu, this error occurs. I hope that helps in some way, even though you have made the change.

Sorry, I didn't make the change in a PR. I got caught up in other work things.
