### ISSUE TITLE
Items that close the menu and items that don't close it

### ISSUE THREAD

**Issue by devel-pa** [negomi/react-burger-menu#94]
Hi,
I have a two levels menu and first level selects what is displayed in the second. 
Another scenario is to have items that close or not on different levels.
There is any way to differentiate the two cases?
Thank you,
Paul

**Comment by devel-pa** [comment]
solved by using `togleMenu`

**Comment by amitava82** [comment]
How is this solved? I could not find any reference to `togleMenu`

**Comment by negomi** [comment]
Hi @amitava82, this issue was closed before I was able to look into it.

There is no `togleMenu` (there is a `toggleMenu` but that's used internally).

If you're having problems, the best thing to do is open a new issue explaining:

1. What you're trying to achieve
2. What you've tried so far
3. How it's not working

Feel free to attach code snippets or a link to a sample repo I can take a look at.

**Comment by devel-pa** [comment]
@amitava82 As the source code is the best reference I observed that the line 

https://github.com/negomi/react-burger-menu/blob/master/dist/react-burger-menu.js#L346

is doing the closing of the menu depending on the small condition `isOpen` when you set `isOpen` as `true` (from docs)

So, now, all the menu items that I want to close the menu after selecting them I have an `onClick` event that call the `toggleMenu` function of this component.

Best,
Paul

**Comment by negomi** [comment]
Ah ok. This works, but it's not advisable for a couple of reasons:

1. `toggleMenu` is an internal method. That means if I decide to change how the component works internally, rename that method, or stop exposing it altogether, your code will break.
2. There is already a way to do what you're doing by passing props, which is the technique [recommended in the React docs](https://facebook.github.io/react/tips/communicate-between-components.html).

The correct way to approach this is to use the `isOpen` and `onStateChange` props. In the simplest scenario (i.e. managing state with a container component rather than a Flux implementation etc.), your code would look something like:

```javascript
class Parent extends React.Component {
  constructor(props) {
    super(props)
    this.state = {menuOpen: false}
  }

  // Keeps your parent component in sync with the menu open state
  handleMenuStateChange(menuState) {
    this.setState({
      menuOpen: menuState.isOpen
    })
  }

  handleChildClick(e) {
    e.preventDefault()
    
    // Do whatever you want the child click to do
    // ...
    
    // Close the menu
    this.setState({
      menuOpen: false
    })
  }
  
  render() {
    return (
      <Menu isOpen={this.state.menuOpen} onStateChange={this.handleMenuStateChange}>
        <a href="" onClick={this.handleChildClick}>Menu item</a>
      </Menu>
    )
  }
}
```
