### ISSUE TITLE
Custom styles for Menu children

### ISSUE THREAD

**Issue by 2easy** [negomi/react-burger-menu#97]
Styles of children of the menu (links and others) are overwritten. My workaround is wrap them in additional element. Same as in #95 I propose the possibility of overwriting styles per element.

**Comment by negomi** [comment]
Hi @2easy, how are you passing styles of the children?

You can pass a styles object with the `bmItem` key and the component will not override these styles:
```javascript
var itemStyles = {bmItem: {color: 'blue'}};
<Menu styles={itemStyles} />
```
I agree it's not well documented, so I should fix that. Does that solve your problem?

**Comment by 2easy** [comment]
Not really, cause I want different styles per element. The case is - I want to center content of the first item (which is user avatar) and not the rest. It could be any element though, ie. different color for logout. I think the best solution is to merge this Menu styles with item styles. I can make PR if you don't have time for it.

**Comment by negomi** [comment]
Ahh I see. That's a use case I would be happy to add as an enhancement. PR would be welcome!

**Comment by aysark** [comment]
@negomi just to piggyback on this, i had a question- is this component strictly for menus/navigation links or can one use it as a docked sidebar with content?  As i'm seeing acouple people raise issues with being able to customize icons for each child which would be needed if it were to be used as a docked sidebar with various different child components.

**Comment by negomi** [comment]
Hi @2easy, the menu now (since v1.10.7) allows different styles to be passed to each child element inline. They will be merged, and not overwritten like before.

Hi @aysark, it can be used for anything :) It was initially intended to just contain a list of similarly styled links (as in the demo), which is why it didn't previously support different styles for individual child elements. But I'm gradually making it more flexible as people request new features, so now what you're describing should work fine!

**Comment by 2easy** [comment]
Perfect! Thanks :) And sorry for no PR, as it turned out, I also had no time.
